### ISSUE TITLE
#2

### ISSUE THREAD

**Issue by novachok** [AnnBond/PhpLaboratory#1]
https://github.com/AnnBond/PhpLaboratory/blob/master/Strings/bonus.php#L14
substr($str, strlen($str)-1, count($str))
=> 
substr($str, -1)

https://github.com/AnnBond/PhpLaboratory/blob/master/Strings/bonus.php#L15
return $newName = ucfirst($str) . $str;
=>
return ucfirst($str) . $str;

https://github.com/AnnBond/PhpLaboratory/blob/master/Strings/bonus.php#L20
твій результат: Alexsandraalexsandra
правильний: Alexsandralexsandra

ще один момент:
https://github.com/AnnBond/PhpLaboratory/blob/master/Strings/index.php#L20
рішення може бути застосованое до рідка 4_4

**Comment by AnnBond** [comment]
Done
